spring.application.name=BloggingPlatform-Spring

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.data.mongodb.uri=${MONGO_CONNECTION_STRING}
spring.data.mongodb.database=${MONGO_DATABASE}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,metrics,loggers,threaddump,httpexchanges,env
management.endpoint.health.show-details=always

spring.datasource.hikari.pool-name=BloggingPlatform-HikariPool
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=45
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.leak-detection-threshold=30000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.auto-commit=true

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB

springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntaxHighlight.activated=true

springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.defaultModelsExpandDepth=1
springdoc.swagger-ui.defaultModelExpandDepth=1
springdoc.show-actuator=false
logging.level.org.mongodb.driver=WARN
logging.level.org.mongodb.driver.cluster=WARN
logging.level.org.mongodb.driver.connection=WARN

jwt.access-token-secret=${ACCESS_TOKEN_SECRET}
jwt.access-token-expiration-ms=${ACCESS_TOKEN_EXPIRATION_MS}
jwt.refresh-token-secret=${REFRESH_TOKEN_SECRET}
jwt.refresh-token-expiration-ms=${REFRESH_TOKEN_EXPIRATION_MS}
app.cookie-secure=false
frontend.base-url=${FRONTEND_BASE_URL}
app.platform-name=DevBlog

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_AUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_AUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
oauth.frontend.redirect.callback.url=${FRONTEND_REDIRECT_CALLBACK_URL}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

logging.level.root=INFO
logging.level.com.bloggingplatform=DEBUG
logging.level.com.bloggingplatform.aspect=INFO
logging.level.com.bloggingplatform.service=DEBUG
logging.level.com.bloggingplatform.repository=DEBUG
logging.level.com.bloggingplatform.controller=INFO
#logging.level.org.springframework.security=TRACE

cloudflare.r2.account-id=${CLOUDFLARE_ACCOUNT_ID}
cloudflare.r2.access-key-id=${CLOUDFLARE_R2_ACCESS_KEY_ID}
cloudflare.r2.secret-access-key=${CLOUDFLARE_R2_SECRET_ACCESS_KEY}
cloudflare.r2.bucket-name=${CLOUDFLARE_R2_BUCKET_NAME}
cloudflare.r2.public-url=${CLOUDFLARE_R2_PUBLIC_URL}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true