spring.application.name=BloggingPlatform-Spring
spring.profiles.active=dev

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.http.path=/graphql
spring.graphql.schema.printer.enabled=true
spring.graphql.schema.locations=classpath:graphql/
logging.file.name=logs/blogging-platform.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

spring.aop.auto=true
spring.aop.proxy-target-class=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.metrics.access=unrestricted
management.metrics.enable.all=true

management.endpoints.web.base-path=/actuator

app.async.core-pool-size=8
app.async.max-pool-size=12
app.async.queue-capacity=400
app.async.keep-alive-seconds=60
app.async.await-termination-seconds=30
app.async.thread-name-prefix=blog-async-